### ISSUE TITLE
file not found error for  .pkl file

### ISSUE THREAD

**Issue by ssbilakeri** [huanghoujing/EANet#32]
Hi,
I am reproducing your paper result . when enabled ps_loss, id_loss, tri_loss as true . im getting bellow error.

what could be the reason?
hepl me to resolve , please .

File "C:\Users\MAHE\anaconda3_new\envs\savitri\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\MAHE\anaconda3_new\envs\savitri\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\project_dir\EANet\package\optim\eanet_trainer.py", line 135, in <module>
    trainer.train_phases()
  File "D:\project_dir\EANet\package\optim\eanet_trainer.py", line 126, in train_phases
    self.train()
  File "D:\project_dir\EANet\package\optim\reid_trainer.py", line 338, in train
    self.trainer.train_one_epoch(trial_run_steps=3 if cfg.trial_run else None)
  File "D:\project_dir\EANet\package\optim\trainer.py", line 35, in train_one_epoch
    for i, batch in enumerate(self.train_loader):
  File "C:\Users\MAHE\anaconda3_new\envs\savitri\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\MAHE\anaconda3_new\envs\savitri\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "C:\Users\MAHE\anaconda3_new\envs\savitri\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\MAHE\anaconda3_new\envs\savitri\lib\site-packages\torch\utils\data\dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\project_dir\EANet\package\data\dataset.py", line 41, in __getitem__
    sample['pap_mask'] = self.get_pap_mask(im_path)
  File "D:\project_dir\EANet\package\data\dataset.py", line 72, in get_pap_mask
    self.im_path_to_kpt = load_pickle(osp.join(self.root, 'im_path_to_kpt.pkl'))
  File "D:\project_dir\EANet\package\utils\file.py", line 34, in load_pickle
    assert osp.exists(path), "File not exists: {}".format(path)
AssertionError: File not exists: D:/project_dir/ReID_dataset/duke\im_path_to_kpt.pkl

**Comment by huanghoujing** [comment]
Hi, I think
- `D:/project_dir/ReID_dataset/duke\im_path_to_kpt.pkl` should be `D:\project_dir\ReID_dataset\duke\im_path_to_kpt.pkl`, since you are using Windows system.
- Besides, you have to make sure this file exists in the disk.
